@startuml
title: Invite Protocol. B and C invites A

participant DHT order 10
participant A order 20 
participant B order 30
participant C order 40

A -> DHT: Announce A
B -> DHT: Announce, Lookup A
B -> B: Setup Feed A \nReplica
DHT --> B: <Port, IP> of A
B -> A: Challenge (A, B)
A -> B: Replicate Feed A
note over A: [Invite accepted]
A -> A: Setup Feed B Replica
B -> A: Feed B replication

...
C -> DHT: Announce, Lookup A
C -> C: Setup Feed A \nReplica
DHT --> C: <IP, Port> of A, B
C -> B: Challenge (A, C)
C -> A: Challenge (A, C)
A -> C: Replicate Feed A
note over A: [Invite accepted]
A -> A: Setup Feed C Replica
C -> A: Feed C replication

@enduml